workflows:
  ios-release:
    name: Salla iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 120

    working_directory: sala_store

    integrations:
      app_store_connect: "SIQ Codemagic"

    environment:
      ios_signing:
        provisioning_profiles:
          - salaaa
        certificates:
          - SallaDistribution

      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up iOS code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
